language: node_js

node_js:
  - "stable"

sudo: required

branches:
  only:
  - master
  - cli-*

addons:
  chrome: stable

before_script:
  - cd angularclient
  - npm install -g @angular/cli
  
script:
  - npm install
  - ng build 
#   - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
